# Generated by Django 6.0.4 on 2026-05-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
